### PR TITLE
Removed unnecessary xs_vec_add

### PR DESCRIPTION
**Pull request by In-line**
I don't see reason for `xs_vec_add(fVectorStart, fNormal, fVectorStart);`. After removing that line I didn't see any side effects.
Also if you disable `register_forward(FM_ShouldCollide, "FM_ShouldCollide_Pre", false);` and come too close to glass snowball will pass through it, because of `xs_vec_add`

### CODE REVIEW

**Comment by Mistrick** [comment]
If delete this addition, snow ball will stuck in player.

**Comment by In-line** [comment]
When can that situation happen?

**Comment by Mistrick** [comment]
Always, on my test server.

**Comment by In-line** [comment]
Interesting, this is not happening on my.

**Pull request closed without merging**
